import { Navbar } from "@/components/layout/Navbar"
import { Footer } from "@/components/layout/Footer"
import { ArrowLeft } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function PrivacyPolicy() {
  return (
    <main className="flex flex-col min-h-screen bg-background">
      <Navbar />
      
      <div className="flex-1 py-32">
        <div className="container mx-auto px-6 max-w-4xl">
          <Button asChild variant="ghost" className="mb-8 pl-0 hover:bg-transparent hover:text-primary transition-colors">
            <Link href="/" className="inline-flex items-center gap-2 text-muted-foreground font-semibold">
              <ArrowLeft className="w-4 h-4" /> Back to Home
            </Link>
          </Button>

          <p className="text-primary font-bold text-xs uppercase tracking-[0.2em] mb-3">Legal Information</p>
          <h1 className="text-4xl md:text-6xl font-black mb-6 leading-tight">Privacy Policy</h1>
          <p className="text-muted-foreground text-sm font-bold uppercase tracking-widest mb-16 pb-8 border-b border-border">
            Last updated: March 2026
          </p>

          <div className="space-y-12 text-muted-foreground leading-relaxed">
            <section>
              <h2 className="text-2xl font-black text-foreground mb-4">1. Introduction</h2>
              <p className="mb-4">
                At Welldropp Technologies ("we," "our," or "us"), we are committed to protecting your privacy strings. This Privacy Policy explains how your personal data is collected, used, and safeguarded when you engage with our intelligent software, APIs, and website services.
              </p>
              <p>
                By using our services, you agree to the collection and use of information in accordance with this policy. If you do not agree with this policy, please do not use our services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-black text-foreground mb-4">2. Information We Collect</h2>
              <p className="mb-4">We collect several different types of information for various purposes to provide and improve our AI solutions to you:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong className="text-foreground">Personal Data:</strong> Email address, first name and last name, phone number, and address.</li>
                <li><strong className="text-foreground">Usage Data:</strong> Information on how the service is accessed and used, including IP addresses, browser types, and interaction metrics.</li>
                <li><strong className="text-foreground">API Telemetry:</strong> Anonymized performance data generated by AI agents to optimize latency and model accuracy.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-black text-foreground mb-4">3. Use of Your Personal Data</h2>
              <p className="mb-4">We use the collected data for various purposes:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>To provide and maintain our Service.</li>
                <li>To notify you about changes to our autonomous agents or infrastructure.</li>
                <li>To provide customer support and improve our ML models.</li>
                <li>To gather analysis or valuable information so that we can improve our Service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-black text-foreground mb-4">4. Data Security</h2>
              <p>
                The security of your data is of our utmost priority, but remember that no method of transmission over the Internet is 100% secure. While we strive to use commercially acceptable, enterprise-grade encryption methods to protect your Personal Data, we cannot guarantee its absolute security.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-black text-foreground mb-4">5. Contact Us</h2>
              <p className="mb-4">
                If you have any questions about this Privacy Policy, please contact our legal and compliance team:
              </p>
              <p className="font-semibold text-primary">privacy@welldropp.com</p>
            </section>
          </div>
        </div>
      </div>

      <Footer />
    </main>
  )
}
